# Database Table Names
TABLE_COMPANY_LEADS = "COMPANYLEADS"
TABLE_LEAD_EVENTS = "LEADEVENTS"

# Column names for CompanyLeads
COL_ID = "ID"
COL_STATE = "STATE"
COL_CREATED_DATE = "CREATEDDATEUTC"
COL_CANCELLATION_REQUEST_DATE = "CANCELLATIONREQUESTDATEUTC"
COL_CANCELLATION_DATE = "CANCELLATIONDATEUTC"
COL_CANCELLATION_REJECTION_DATE = "CANCELLATIONREJECTIONDATEUTC"
COL_SOLD_EMPLOYEE = "SOLDEMPLOYEE"
COL_CANCELLED_EMPLOYEE = "CANCELLEDEMPLOYEE"
COL_UPDATED_DATE = "UPDATEDDATEUTC"

# Column names for EventLeads
COL_EVENT_ID = "ID"
COL_EVENT_TYPE = "EVENTTYPE"
COL_EVENT_EMPLOYEE = "EVENTEMPLOYEE"
COL_EVENT_DATE = "EVENTDATE"
COL_EVENT_LEAD_ID = "LEADID"
COL_EVENT_UPDATED_DATE_UTC = "UPDATEDDATEUTC"

# Event Types
EVENT_LEAD_SOLD = "LeadSold"
EVENT_LEAD_REQUESTED_CANCELLATION = "LeadRequestedCancellation"
EVENT_LEAD_CANCELLED = "LeadCancelled"
EVENT_LEAD_CANCELLATION_REJECTED = "LeadCancellationRejected"

# Employee name if NULL
UNKNOWN_EMPLOYEE = "Unknown"
